INSERT OR IGNORE INTO tags (key, label, class_name) VALUES ('design', 'Diseño integral', 'bg-black text-white');
INSERT OR IGNORE INTO tags (key, label, class_name) VALUES ('graphic', 'Gráfico', 'bg-dora-sky text-black');
INSERT OR IGNORE INTO tags (key, label, class_name) VALUES ('editorial', 'Editorial', 'bg-dora-pink text-black');
INSERT OR IGNORE INTO tags (key, label, class_name) VALUES ('branding', 'Branding', 'bg-dora-red text-black');
INSERT OR IGNORE INTO tags (key, label, class_name) VALUES ('illustration', 'Ilustración', 'bg-dora-yellow text-black');
INSERT OR IGNORE INTO projects (id, slug, title, status, color_class, digest, summary, created_at, updated_at, published_at) VALUES ('legacy-una-ventana-para-el-arte', 'una-ventana-para-el-arte', 'Una ventana para el arte', 'published', 'bg-dora-pink', 'Sistema editorial para el Museo de Artes Visuales MAVI UC, que promueve una experiencia museográfica reflexiva e interactiva.', 'Impulsado por el Departamento de Educación e Inclusión del MAVI UC, este proyecto buscó transformar la experiencia de los visitantes mediante folletos que promovieran una interacción reflexiva con las obras.

Ante el desafío de producir un material atractivo, adaptable y eficiente, se implementó un sistema gráfico que preservaba la identidad visual del museo, pero con suficiente flexibilidad para adaptarse a la estética particular de cada exposición. Esta solución optimizó los procesos de diseño y distribución, consolidándose como un formato replicable que se materializó con tres exposiciones que utilizaron este modelo; sentando las bases para futuras ediciones.', 1787784320335, 1787784320335, 1787784320335);
INSERT OR IGNORE INTO project_tags (project_id, tag_key) VALUES ('legacy-una-ventana-para-el-arte', 'editorial');
INSERT OR IGNORE INTO media (id, project_id, role, media_type, object_key, public_url, alt, class_name, sort_order, mime_type, created_at) VALUES ('legacy-una-ventana-para-el-arte-cover', 'legacy-una-ventana-para-el-arte', 'cover', 'image', 'una-ventana-para-el-arte/cover.png', '/una-ventana-para-el-arte/cover.png', 'Una ventana para el arte', '', 0, 'image/png', 1787784320335);
INSERT OR IGNORE INTO media (id, project_id, role, media_type, object_key, public_url, alt, class_name, sort_order, mime_type, created_at) VALUES ('legacy-una-ventana-para-el-arte-gallery-0', 'legacy-una-ventana-para-el-arte', 'gallery', 'image', 'una-ventana-para-el-arte/1.png', '/una-ventana-para-el-arte/1.png', 'Una ventana para el arte', '', 0, 'image/png', 1787784320335);
INSERT OR IGNORE INTO media (id, project_id, role, media_type, object_key, public_url, alt, class_name, sort_order, mime_type, created_at) VALUES ('legacy-una-ventana-para-el-arte-gallery-1', 'legacy-una-ventana-para-el-arte', 'gallery', 'image', 'una-ventana-para-el-arte/2.png', '/una-ventana-para-el-arte/2.png', 'Una ventana para el arte', '', 1, 'image/png', 1787784320335);
INSERT OR IGNORE INTO media (id, project_id, role, media_type, object_key, public_url, alt, class_name, sort_order, mime_type, created_at) VALUES ('legacy-una-ventana-para-el-arte-gallery-2', 'legacy-una-ventana-para-el-arte', 'gallery', 'image', 'una-ventana-para-el-arte/3.png', '/una-ventana-para-el-arte/3.png', 'Una ventana para el arte', 'scale-120', 2, 'image/png', 1787784320335);
INSERT OR IGNORE INTO media (id, project_id, role, media_type, object_key, public_url, alt, class_name, sort_order, mime_type, created_at) VALUES ('legacy-una-ventana-para-el-arte-gallery-3', 'legacy-una-ventana-para-el-arte', 'gallery', 'image', 'una-ventana-para-el-arte/4.png', '/una-ventana-para-el-arte/4.png', 'Una ventana para el arte', '', 3, 'image/png', 1787784320335);
INSERT OR IGNORE INTO media (id, project_id, role, media_type, object_key, public_url, alt, class_name, sort_order, mime_type, created_at) VALUES ('legacy-una-ventana-para-el-arte-gallery-4', 'legacy-una-ventana-para-el-arte', 'gallery', 'image', 'una-ventana-para-el-arte/5.png', '/una-ventana-para-el-arte/5.png', 'Una ventana para el arte', '', 4, 'image/png', 1787784320335);
INSERT OR IGNORE INTO media (id, project_id, role, media_type, object_key, public_url, alt, class_name, sort_order, mime_type, created_at) VALUES ('legacy-una-ventana-para-el-arte-gallery-5', 'legacy-una-ventana-para-el-arte', 'gallery', 'image', 'una-ventana-para-el-arte/6.png', '/una-ventana-para-el-arte/6.png', 'Una ventana para el arte', '', 5, 'image/png', 1787784320335);
INSERT OR IGNORE INTO media (id, project_id, role, media_type, object_key, public_url, alt, class_name, sort_order, mime_type, created_at) VALUES ('legacy-una-ventana-para-el-arte-gallery-6', 'legacy-una-ventana-para-el-arte', 'gallery', 'image', 'una-ventana-para-el-arte/7.png', '/una-ventana-para-el-arte/7.png', 'Una ventana para el arte', '', 6, 'image/png', 1787784320335);
INSERT OR IGNORE INTO media (id, project_id, role, media_type, object_key, public_url, alt, class_name, sort_order, mime_type, created_at) VALUES ('legacy-una-ventana-para-el-arte-gallery-7', 'legacy-una-ventana-para-el-arte', 'gallery', 'image', 'una-ventana-para-el-arte/8.png', '/una-ventana-para-el-arte/8.png', 'Una ventana para el arte', '', 7, 'image/png', 1787784320335);
INSERT OR IGNORE INTO projects (id, slug, title, status, color_class, digest, summary, created_at, updated_at, published_at) VALUES ('legacy-kombucha-loyca', 'kombucha-loyca', 'Kombucha Loyca', 'published', 'bg-dora-orange', 'Rebranding para reposicionar una bebida artesanal en el mercado gastronómico contemporáneo.', 'Loyca impulsó un rebranding con el objetivo de aumentar su alcance en el mercado, reposicionando su kombucha más allá del nicho orgánico convencional, para consolidarse como una alternativa versátil y gourmet en el mercado gastronómico; orientándose a restaurantes, coctelería de autor y cafés de especialidad. 

El nuevo enfoque de identidad mantiene la esencia artesanal de Loyca, combinándola con un carácter contemporáneo, fresco y experimental. Este replanteamiento fortaleció la identidad de la marca, facilitando también su integración en nuevos contextos de consumo, aumentando su percepción de calidad, autenticidad y adaptabilidad.', 1787784320335, 1787784320335, 1787784320335);
INSERT OR IGNORE INTO project_tags (project_id, tag_key) VALUES ('legacy-kombucha-loyca', 'branding');
INSERT OR IGNORE INTO media (id, project_id, role, media_type, object_key, public_url, alt, class_name, sort_order, mime_type, created_at) VALUES ('legacy-kombucha-loyca-cover', 'legacy-kombucha-loyca', 'cover', 'image', 'kombucha-loyca/cover.png', '/kombucha-loyca/cover.png', 'Kombucha Loyca', '', 0, 'image/png', 1787784320335);
INSERT OR IGNORE INTO media (id, project_id, role, media_type, object_key, public_url, alt, class_name, sort_order, mime_type, created_at) VALUES ('legacy-kombucha-loyca-gallery-0', 'legacy-kombucha-loyca', 'gallery', 'image', 'kombucha-loyca/1.png', '/kombucha-loyca/1.png', 'Kombucha Loyca', '', 0, 'image/png', 1787784320335);
INSERT OR IGNORE INTO media (id, project_id, role, media_type, object_key, public_url, alt, class_name, sort_order, mime_type, created_at) VALUES ('legacy-kombucha-loyca-gallery-1', 'legacy-kombucha-loyca', 'gallery', 'image', 'kombucha-loyca/2.png', '/kombucha-loyca/2.png', 'Kombucha Loyca', '', 1, 'image/png', 1787784320335);
INSERT OR IGNORE INTO media (id, project_id, role, media_type, object_key, public_url, alt, class_name, sort_order, mime_type, created_at) VALUES ('legacy-kombucha-loyca-gallery-2', 'legacy-kombucha-loyca', 'gallery', 'image', 'kombucha-loyca/3.png', '/kombucha-loyca/3.png', 'Kombucha Loyca', '', 2, 'image/png', 1787784320335);
INSERT OR IGNORE INTO media (id, project_id, role, media_type, object_key, public_url, alt, class_name, sort_order, mime_type, created_at) VALUES ('legacy-kombucha-loyca-gallery-3', 'legacy-kombucha-loyca', 'gallery', 'image', 'kombucha-loyca/4.png', '/kombucha-loyca/4.png', 'Kombucha Loyca', '', 3, 'image/png', 1787784320335);
INSERT OR IGNORE INTO projects (id, slug, title, status, color_class, digest, summary, created_at, updated_at, published_at) VALUES ('legacy-frankenstein', 'frankenstein', 'Frankenstein', 'published', 'bg-dora-sky', 'Afiche cultural desarrollado como proyecto universitario para conmemorar los 200 años de Frankenstein.', 'Proyecto universitario de difusión cultural, desarrollado para conmemorar los más de 200 años de la publicación de Frankenstein (1818) y acercar su legado a nuevas generaciones.  El afiche se centra en reinterpretar una de las principales tensiones de la obra: la contraposición entre la bondad del monstruo y la maldad del ser humano.
Bajo este concepto, la propuesta invita a una lectura contemporánea de la obra, abordando los dilemas éticos y existenciales que plantea. La propuesta utiliza recursos visuales metafóricos para enriquecer la interpretación y promover una conexión crítica y emocional con el espectador contemporáneo.', 1787784320335, 1787784320335, 1787784320335);
INSERT OR IGNORE INTO project_tags (project_id, tag_key) VALUES ('legacy-frankenstein', 'graphic');
INSERT OR IGNORE INTO media (id, project_id, role, media_type, object_key, public_url, alt, class_name, sort_order, mime_type, created_at) VALUES ('legacy-frankenstein-cover', 'legacy-frankenstein', 'cover', 'image', 'frankenstein/cover.png', '/frankenstein/cover.png', 'Frankenstein', '', 0, 'image/png', 1787784320335);
INSERT OR IGNORE INTO media (id, project_id, role, media_type, object_key, public_url, alt, class_name, sort_order, mime_type, created_at) VALUES ('legacy-frankenstein-gallery-0', 'legacy-frankenstein', 'gallery', 'image', 'frankenstein/1.png', '/frankenstein/1.png', 'Frankenstein', '', 0, 'image/png', 1787784320335);
INSERT OR IGNORE INTO media (id, project_id, role, media_type, object_key, public_url, alt, class_name, sort_order, mime_type, created_at) VALUES ('legacy-frankenstein-gallery-1', 'legacy-frankenstein', 'gallery', 'video', 'frankenstein/2.mp4', '/frankenstein/2.mp4', 'Frankenstein', '', 1, 'video/mp4', 1787784320335);
INSERT OR IGNORE INTO media (id, project_id, role, media_type, object_key, public_url, alt, class_name, sort_order, mime_type, created_at) VALUES ('legacy-frankenstein-gallery-2', 'legacy-frankenstein', 'gallery', 'image', 'frankenstein/3.png', '/frankenstein/3.png', 'Frankenstein', '', 2, 'image/png', 1787784320335);
INSERT OR IGNORE INTO media (id, project_id, role, media_type, object_key, public_url, alt, class_name, sort_order, mime_type, created_at) VALUES ('legacy-frankenstein-gallery-3', 'legacy-frankenstein', 'gallery', 'image', 'frankenstein/4.gif', '/frankenstein/4.gif', 'Frankenstein', '', 3, 'image/gif', 1787784320335);
INSERT OR IGNORE INTO media (id, project_id, role, media_type, object_key, public_url, alt, class_name, sort_order, mime_type, created_at) VALUES ('legacy-frankenstein-gallery-4', 'legacy-frankenstein', 'gallery', 'image', 'frankenstein/5.png', '/frankenstein/5.png', 'Frankenstein', '', 4, 'image/png', 1787784320335);
INSERT OR IGNORE INTO projects (id, slug, title, status, color_class, digest, summary, created_at, updated_at, published_at) VALUES ('legacy-chao-reunionitis', 'chao-reunionitis', 'Chao Reunionitis', 'published', 'bg-dora-green', 'Campaña gráfica interna para Teck, orientada a promover una gestión eficiente de las reuniones de trabajo.', 'Frente a la problemática del exceso de reuniones y su impacto en la productividad y el bienestar de los equipos, un equipo de liderazgo interno de Teck impulsó una campaña de sensibilización orientada a promover una gestión más eficiente del tiempo durante las reuniones de trabajo.

La campaña tomó como eje conceptual la "reunionitis", un término humorístico que permitió abordar el tema de forma cercana y amena, facilitando la identificación y reflexión de los colaboradores. A partir de este concepto se desarrollaron piezas gráficas ilustradas que, mediante el humor, transmitieron buenas prácticas para planificar y asistir a reuniones de manera más efectiva. La estrategia se complementó con acciones de difusión interna que reforzaron el mensaje en distintos espacios de trabajo, favoreciendo la adopción de comportamientos más eficientes.      ', 1787784320335, 1787784320335, 1787784320335);
INSERT OR IGNORE INTO project_tags (project_id, tag_key) VALUES ('legacy-chao-reunionitis', 'graphic');
INSERT OR IGNORE INTO project_tags (project_id, tag_key) VALUES ('legacy-chao-reunionitis', 'illustration');
INSERT OR IGNORE INTO media (id, project_id, role, media_type, object_key, public_url, alt, class_name, sort_order, mime_type, created_at) VALUES ('legacy-chao-reunionitis-cover', 'legacy-chao-reunionitis', 'cover', 'image', 'chao-reunionitis/cover.png', '/chao-reunionitis/cover.png', 'Chao Reunionitis', '', 0, 'image/png', 1787784320335);
INSERT OR IGNORE INTO media (id, project_id, role, media_type, object_key, public_url, alt, class_name, sort_order, mime_type, created_at) VALUES ('legacy-chao-reunionitis-gallery-0', 'legacy-chao-reunionitis', 'gallery', 'image', 'chao-reunionitis/1.png', '/chao-reunionitis/1.png', 'Chao Reunionitis', 'object-bottom', 0, 'image/png', 1787784320335);
INSERT OR IGNORE INTO media (id, project_id, role, media_type, object_key, public_url, alt, class_name, sort_order, mime_type, created_at) VALUES ('legacy-chao-reunionitis-gallery-1', 'legacy-chao-reunionitis', 'gallery', 'image', 'chao-reunionitis/2.png', '/chao-reunionitis/2.png', 'Chao Reunionitis', 'object-top', 1, 'image/png', 1787784320335);
INSERT OR IGNORE INTO media (id, project_id, role, media_type, object_key, public_url, alt, class_name, sort_order, mime_type, created_at) VALUES ('legacy-chao-reunionitis-gallery-2', 'legacy-chao-reunionitis', 'gallery', 'image', 'chao-reunionitis/3.png', '/chao-reunionitis/3.png', 'Chao Reunionitis', 'object-bottom', 2, 'image/png', 1787784320335);
INSERT OR IGNORE INTO media (id, project_id, role, media_type, object_key, public_url, alt, class_name, sort_order, mime_type, created_at) VALUES ('legacy-chao-reunionitis-gallery-3', 'legacy-chao-reunionitis', 'gallery', 'image', 'chao-reunionitis/4.png', '/chao-reunionitis/4.png', 'Chao Reunionitis', 'object-top', 3, 'image/png', 1787784320335);
INSERT OR IGNORE INTO media (id, project_id, role, media_type, object_key, public_url, alt, class_name, sort_order, mime_type, created_at) VALUES ('legacy-chao-reunionitis-gallery-4', 'legacy-chao-reunionitis', 'gallery', 'image', 'chao-reunionitis/5.png', '/chao-reunionitis/5.png', 'Chao Reunionitis', 'object-center', 4, 'image/png', 1787784320335);
INSERT OR IGNORE INTO media (id, project_id, role, media_type, object_key, public_url, alt, class_name, sort_order, mime_type, created_at) VALUES ('legacy-chao-reunionitis-gallery-5', 'legacy-chao-reunionitis', 'gallery', 'image', 'chao-reunionitis/6.png', '/chao-reunionitis/6.png', 'Chao Reunionitis', 'object-center', 5, 'image/png', 1787784320335);
INSERT OR IGNORE INTO media (id, project_id, role, media_type, object_key, public_url, alt, class_name, sort_order, mime_type, created_at) VALUES ('legacy-chao-reunionitis-gallery-6', 'legacy-chao-reunionitis', 'gallery', 'image', 'chao-reunionitis/7.png', '/chao-reunionitis/7.png', 'Chao Reunionitis', 'object-center', 6, 'image/png', 1787784320335);
INSERT OR IGNORE INTO media (id, project_id, role, media_type, object_key, public_url, alt, class_name, sort_order, mime_type, created_at) VALUES ('legacy-chao-reunionitis-gallery-7', 'legacy-chao-reunionitis', 'gallery', 'image', 'chao-reunionitis/8.png', '/chao-reunionitis/8.png', 'Chao Reunionitis', 'object-center', 7, 'image/png', 1787784320335);
INSERT OR IGNORE INTO projects (id, slug, title, status, color_class, digest, summary, created_at, updated_at, published_at) VALUES ('legacy-a-solas-el-jardin', 'a-solas-el-jardin', 'A solas, el jardín', 'draft', 'bg-dora-violet', 'Publicación editorial ilustrada que aborda la soledad emocional en jóvenes a través de una metáfora visual y relatos personales.', 'Proyecto de título enfocado en la problemática de la soledad emocional en personas jóvenes, desarrollado a través de una publicación editorial ilustrada. El proyecto utiliza representaciones metafóricas de experiencias cotidianas para abrir espacios de interpretación e identificación personal, acompañadas de relatos anónimos que invitan a la reflexión y al ejercicio introspectivo.

La propuesta busca generar una experiencia de lectura sensible y auténtica, combinando una atmósfera visual introspectiva con el carácter crudo de las vivencias narradas. El desarrollo del proyecto implicó un extenso proceso de investigación, entrevistas personales, iteración de contenidos y validaciones cualitativas, con el objetivo de construir un dispositivo editorial capaz de dialogar de manera genuina con las emociones del lector.', 1787784320335, 1787784320335, NULL);
INSERT OR IGNORE INTO project_tags (project_id, tag_key) VALUES ('legacy-a-solas-el-jardin', 'editorial');
INSERT OR IGNORE INTO project_tags (project_id, tag_key) VALUES ('legacy-a-solas-el-jardin', 'illustration');
INSERT OR IGNORE INTO media (id, project_id, role, media_type, object_key, public_url, alt, class_name, sort_order, mime_type, created_at) VALUES ('legacy-a-solas-el-jardin-cover', 'legacy-a-solas-el-jardin', 'cover', 'image', 'una-ventana-para-el-arte/cover.png', '/una-ventana-para-el-arte/cover.png', 'A solas, el jardín', '', 0, 'image/png', 1787784320335);
INSERT OR IGNORE INTO media (id, project_id, role, media_type, object_key, public_url, alt, class_name, sort_order, mime_type, created_at) VALUES ('legacy-a-solas-el-jardin-gallery-0', 'legacy-a-solas-el-jardin', 'gallery', 'image', 'una-ventana-para-el-arte/1.png', '/una-ventana-para-el-arte/1.png', 'Una ventana para el arte', '', 0, 'image/png', 1787784320335);
INSERT OR IGNORE INTO media (id, project_id, role, media_type, object_key, public_url, alt, class_name, sort_order, mime_type, created_at) VALUES ('legacy-a-solas-el-jardin-gallery-1', 'legacy-a-solas-el-jardin', 'gallery', 'image', 'una-ventana-para-el-arte/2.png', '/una-ventana-para-el-arte/2.png', 'Una ventana para el arte', '', 1, 'image/png', 1787784320335);
INSERT OR IGNORE INTO media (id, project_id, role, media_type, object_key, public_url, alt, class_name, sort_order, mime_type, created_at) VALUES ('legacy-a-solas-el-jardin-gallery-2', 'legacy-a-solas-el-jardin', 'gallery', 'image', 'una-ventana-para-el-arte/3.png', '/una-ventana-para-el-arte/3.png', 'Una ventana para el arte', '', 2, 'image/png', 1787784320335);
INSERT OR IGNORE INTO media (id, project_id, role, media_type, object_key, public_url, alt, class_name, sort_order, mime_type, created_at) VALUES ('legacy-a-solas-el-jardin-gallery-3', 'legacy-a-solas-el-jardin', 'gallery', 'image', 'una-ventana-para-el-arte/4.png', '/una-ventana-para-el-arte/4.png', 'Una ventana para el arte', '', 3, 'image/png', 1787784320335);
INSERT OR IGNORE INTO media (id, project_id, role, media_type, object_key, public_url, alt, class_name, sort_order, mime_type, created_at) VALUES ('legacy-a-solas-el-jardin-gallery-4', 'legacy-a-solas-el-jardin', 'gallery', 'image', 'una-ventana-para-el-arte/5.png', '/una-ventana-para-el-arte/5.png', 'Una ventana para el arte', '', 4, 'image/png', 1787784320335);
INSERT OR IGNORE INTO media (id, project_id, role, media_type, object_key, public_url, alt, class_name, sort_order, mime_type, created_at) VALUES ('legacy-a-solas-el-jardin-gallery-5', 'legacy-a-solas-el-jardin', 'gallery', 'image', 'una-ventana-para-el-arte/6.png', '/una-ventana-para-el-arte/6.png', 'Una ventana para el arte', '', 5, 'image/png', 1787784320335);
INSERT OR IGNORE INTO media (id, project_id, role, media_type, object_key, public_url, alt, class_name, sort_order, mime_type, created_at) VALUES ('legacy-a-solas-el-jardin-gallery-6', 'legacy-a-solas-el-jardin', 'gallery', 'image', 'una-ventana-para-el-arte/7.png', '/una-ventana-para-el-arte/7.png', 'Una ventana para el arte', '', 6, 'image/png', 1787784320335);
INSERT OR IGNORE INTO media (id, project_id, role, media_type, object_key, public_url, alt, class_name, sort_order, mime_type, created_at) VALUES ('legacy-a-solas-el-jardin-gallery-7', 'legacy-a-solas-el-jardin', 'gallery', 'image', 'una-ventana-para-el-arte/8.png', '/una-ventana-para-el-arte/8.png', 'Una ventana para el arte', '', 7, 'image/png', 1787784320335);
INSERT OR IGNORE INTO projects (id, slug, title, status, color_class, digest, summary, created_at, updated_at, published_at) VALUES ('legacy-¿?', '¿?', '¿?', 'draft', 'bg-dora-pink', '', '', 1787784320335, 1787784320335, NULL);
INSERT OR IGNORE INTO project_tags (project_id, tag_key) VALUES ('legacy-¿?', 'editorial');
INSERT OR IGNORE INTO media (id, project_id, role, media_type, object_key, public_url, alt, class_name, sort_order, mime_type, created_at) VALUES ('legacy-¿?-cover', 'legacy-¿?', 'cover', 'image', 'una-ventana-para-el-arte/cover.png', '/una-ventana-para-el-arte/cover.png', '¿?', '', 0, 'image/png', 1787784320335);
INSERT OR IGNORE INTO media (id, project_id, role, media_type, object_key, public_url, alt, class_name, sort_order, mime_type, created_at) VALUES ('legacy-¿?-gallery-0', 'legacy-¿?', 'gallery', 'image', 'una-ventana-para-el-arte/1.png', '/una-ventana-para-el-arte/1.png', 'Una ventana para el arte', '', 0, 'image/png', 1787784320335);
INSERT OR IGNORE INTO media (id, project_id, role, media_type, object_key, public_url, alt, class_name, sort_order, mime_type, created_at) VALUES ('legacy-¿?-gallery-1', 'legacy-¿?', 'gallery', 'image', 'una-ventana-para-el-arte/2.png', '/una-ventana-para-el-arte/2.png', 'Una ventana para el arte', '', 1, 'image/png', 1787784320335);
INSERT OR IGNORE INTO media (id, project_id, role, media_type, object_key, public_url, alt, class_name, sort_order, mime_type, created_at) VALUES ('legacy-¿?-gallery-2', 'legacy-¿?', 'gallery', 'image', 'una-ventana-para-el-arte/3.png', '/una-ventana-para-el-arte/3.png', 'Una ventana para el arte', '', 2, 'image/png', 1787784320335);
INSERT OR IGNORE INTO media (id, project_id, role, media_type, object_key, public_url, alt, class_name, sort_order, mime_type, created_at) VALUES ('legacy-¿?-gallery-3', 'legacy-¿?', 'gallery', 'image', 'una-ventana-para-el-arte/4.png', '/una-ventana-para-el-arte/4.png', 'Una ventana para el arte', '', 3, 'image/png', 1787784320335);
INSERT OR IGNORE INTO media (id, project_id, role, media_type, object_key, public_url, alt, class_name, sort_order, mime_type, created_at) VALUES ('legacy-¿?-gallery-4', 'legacy-¿?', 'gallery', 'image', 'una-ventana-para-el-arte/5.png', '/una-ventana-para-el-arte/5.png', 'Una ventana para el arte', '', 4, 'image/png', 1787784320335);
INSERT OR IGNORE INTO media (id, project_id, role, media_type, object_key, public_url, alt, class_name, sort_order, mime_type, created_at) VALUES ('legacy-¿?-gallery-5', 'legacy-¿?', 'gallery', 'image', 'una-ventana-para-el-arte/6.png', '/una-ventana-para-el-arte/6.png', 'Una ventana para el arte', '', 5, 'image/png', 1787784320335);
INSERT OR IGNORE INTO media (id, project_id, role, media_type, object_key, public_url, alt, class_name, sort_order, mime_type, created_at) VALUES ('legacy-¿?-gallery-6', 'legacy-¿?', 'gallery', 'image', 'una-ventana-para-el-arte/7.png', '/una-ventana-para-el-arte/7.png', 'Una ventana para el arte', '', 6, 'image/png', 1787784320335);
INSERT OR IGNORE INTO media (id, project_id, role, media_type, object_key, public_url, alt, class_name, sort_order, mime_type, created_at) VALUES ('legacy-¿?-gallery-7', 'legacy-¿?', 'gallery', 'image', 'una-ventana-para-el-arte/8.png', '/una-ventana-para-el-arte/8.png', 'Una ventana para el arte', '', 7, 'image/png', 1787784320335);
INSERT OR IGNORE INTO projects (id, slug, title, status, color_class, digest, summary, created_at, updated_at, published_at) VALUES ('legacy-hicigrafia', 'hicigrafia', 'Hicigrafía', 'published', 'bg-dora-yellow', 'Proyecto de ilustración y arte gráfico que nace de una forma particular de mirar el mundo.', 'Hicigrafía es un proyecto de ilustración autoral que nace de la búsqueda por encontrar una forma propia de mirar el mundo. Su nombre surge de la firma “hicidora”, seudónimo construido a partir de Isidora, y se transforma en hicigrafía como una manera de nombrar este universo de imágenes.

      Las ilustraciones toman situaciones, objetos y personajes reconocibles para transformarlos en escenas absurdas, humorísticas o simbólicas, donde algo aparentemente simple puede esconder una segunda lectura. A través de la caricatura y las asociaciones inesperadas, el proyecto explora temas y experiencias más complejas desde lugares cercanos, buscando provocar una sonrisa, una reflexión o ese momento en que algo hace sentido de una manera inesperada.
      ', 1787784320335, 1787784320335, 1787784320335);
INSERT OR IGNORE INTO project_tags (project_id, tag_key) VALUES ('legacy-hicigrafia', 'illustration');
INSERT OR IGNORE INTO media (id, project_id, role, media_type, object_key, public_url, alt, class_name, sort_order, mime_type, created_at) VALUES ('legacy-hicigrafia-cover', 'legacy-hicigrafia', 'cover', 'image', 'hicigrafia/cover.png', '/hicigrafia/cover.png', 'Hicigrafía', '', 0, 'image/png', 1787784320335);
INSERT OR IGNORE INTO media (id, project_id, role, media_type, object_key, public_url, alt, class_name, sort_order, mime_type, created_at) VALUES ('legacy-hicigrafia-gallery-0', 'legacy-hicigrafia', 'gallery', 'image', 'hicigrafia/1.png', '/hicigrafia/1.png', 'Una ventana para el arte', '', 0, 'image/png', 1787784320335);
INSERT OR IGNORE INTO media (id, project_id, role, media_type, object_key, public_url, alt, class_name, sort_order, mime_type, created_at) VALUES ('legacy-hicigrafia-gallery-1', 'legacy-hicigrafia', 'gallery', 'image', 'hicigrafia/2.png', '/hicigrafia/2.png', 'Una ventana para el arte', '', 1, 'image/png', 1787784320335);
INSERT OR IGNORE INTO media (id, project_id, role, media_type, object_key, public_url, alt, class_name, sort_order, mime_type, created_at) VALUES ('legacy-hicigrafia-gallery-2', 'legacy-hicigrafia', 'gallery', 'image', 'hicigrafia/3.jpeg', '/hicigrafia/3.jpeg', 'Una ventana para el arte', 'scale-140', 2, 'image/jpeg', 1787784320335);
INSERT OR IGNORE INTO media (id, project_id, role, media_type, object_key, public_url, alt, class_name, sort_order, mime_type, created_at) VALUES ('legacy-hicigrafia-gallery-3', 'legacy-hicigrafia', 'gallery', 'image', 'hicigrafia/4.png', '/hicigrafia/4.png', 'Una ventana para el arte', 'scale-140', 3, 'image/png', 1787784320335);
INSERT OR IGNORE INTO media (id, project_id, role, media_type, object_key, public_url, alt, class_name, sort_order, mime_type, created_at) VALUES ('legacy-hicigrafia-gallery-4', 'legacy-hicigrafia', 'gallery', 'image', 'hicigrafia/5.png', '/hicigrafia/5.png', 'Una ventana para el arte', 'scale-140', 4, 'image/png', 1787784320335);
INSERT OR IGNORE INTO media (id, project_id, role, media_type, object_key, public_url, alt, class_name, sort_order, mime_type, created_at) VALUES ('legacy-hicigrafia-gallery-5', 'legacy-hicigrafia', 'gallery', 'image', 'hicigrafia/6.png', '/hicigrafia/6.png', 'Una ventana para el arte', 'scale-140', 5, 'image/png', 1787784320335);
INSERT OR IGNORE INTO media (id, project_id, role, media_type, object_key, public_url, alt, class_name, sort_order, mime_type, created_at) VALUES ('legacy-hicigrafia-gallery-6', 'legacy-hicigrafia', 'gallery', 'image', 'hicigrafia/7.png', '/hicigrafia/7.png', 'Una ventana para el arte', '', 6, 'image/png', 1787784320335);
INSERT OR IGNORE INTO media (id, project_id, role, media_type, object_key, public_url, alt, class_name, sort_order, mime_type, created_at) VALUES ('legacy-hicigrafia-gallery-7', 'legacy-hicigrafia', 'gallery', 'image', 'hicigrafia/8.png', '/hicigrafia/8.png', 'Una ventana para el arte', '', 7, 'image/png', 1787784320335);
INSERT OR IGNORE INTO media (id, project_id, role, media_type, object_key, public_url, alt, class_name, sort_order, mime_type, created_at) VALUES ('legacy-hicigrafia-gallery-8', 'legacy-hicigrafia', 'gallery', 'image', 'hicigrafia/9.jpeg', '/hicigrafia/9.jpeg', 'Una ventana para el arte', '', 8, 'image/jpeg', 1787784320335);
INSERT OR IGNORE INTO media (id, project_id, role, media_type, object_key, public_url, alt, class_name, sort_order, mime_type, created_at) VALUES ('legacy-hicigrafia-gallery-9', 'legacy-hicigrafia', 'gallery', 'image', 'hicigrafia/10.png', '/hicigrafia/10.png', 'Una ventana para el arte', '', 9, 'image/png', 1787784320335);
